# Generated by Django 4.2.4 on 2023-10-04 03:58

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_tecnoamf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudante',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='estudante',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='nome_curso',
            new_name='curso',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='id',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='nome',
        ),
        migrations.AddField(
            model_name='estudante',
            name='foto',
            field=models.ImageField(default=None, upload_to='curso/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudante',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
